# Generated by Django 5.2.2 on 2025-08-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='extracted_text',
            field=models.TextField(default=''),
        ),
    ]
